<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Manejo de Errores</title>
</head>
<body>
    <script>
        //Curso 16 Manejo de errores

        try {
            console.log("En el try se agrega el codigo a evaluar");
            noExiste;
            console.log("segundo try")
        } catch (error) {
            console.log("Catch, captura cualquier error surgido o lanzado en el try");
        }finally{
            console.log("el bloque finally se ejecutara siempre al final de un bloque try-catch");
        }

        try {
            let numero = 10;
            if (isNaN(numero)){
                throw new Error("El caracter introducido no es un numero")
            }
        } catch (error) {
            console.log(`Se produjo el siguiente error:${error}`);
        }
    </script>
</body>
</html>